
name: GitHub Actions Demo

on: 
  push:
    branches: main
    paths-ignore: .github
  pull_request:
    branches: main
  schedule:
    - cron: 15 6 * * SUN

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Step1
        run: echo Event name is ${{ github.event_name }}
      - name: Step2
        run: echo Branch name is ${{ github.ref }}
  
